-- Generated by Supabase CLI. Apply after the two existing Market Talk migrations.
-- Side-only metadata. No UPDATE/INSERT/DELETE of main market or comic data.
begin;
create view icg_side.market_talk_source_v1 with (security_invoker=true) as
select snapshot_date::text, us10y, vix, oil_wti, spy_change, nasdaq_change,
       dollar_index, hy_spread, fear_greed, created_at, data_quality
from icg.daily_snapshots;
revoke all on icg_side.market_talk_source_v1 from public,anon,authenticated;
grant select on icg_side.market_talk_source_v1 to service_role;

create table icg_side.talk_slots (
 page_id text not null references icg_side.facebook_page_policy,
 slot_date date not null, due_at timestamptz not null, window_end timestamptz not null,
 status text not null, reason_code text not null, revision text,
 updated_at timestamptz not null default clock_timestamp(), primary key(page_id,slot_date),
 check(due_at < window_end)
);
create index talk_slots_pending on icg_side.talk_slots(status,window_end);
create table icg_side.talk_run_events (
 id bigint generated always as identity primary key,
 page_id text not null references icg_side.facebook_page_policy,
 slot_date date not null, run_id text not null, stage text not null,
 status text not null, reason_code text not null, revision text,
 at timestamptz not null default clock_timestamp()
);
create index talk_run_events_slot on icg_side.talk_run_events(page_id,slot_date,at desc);
create table icg_side.talk_model_attempts (
 page_id text not null, request_key text not null, phase text not null check(phase in ('generation','review')),
 state text not null check(state in ('RESERVED','COMPLETE','FAILED','UNKNOWN')),
 updated_at timestamptz not null default clock_timestamp(), primary key(page_id,request_key),
 foreign key(page_id,request_key) references icg_side.talk_costs(page_id,request_key)
);

create function icg_side.talk_contract_version() returns integer
language sql stable security invoker set search_path='' as $$ select 3 $$;

create function icg_side.talk_record_outcome(p_page text,p_day date,p_run text,p_stage text,p_status text,p_code text,p_revision text)
returns boolean language plpgsql security invoker set search_path='' as $$
begin
 if p_day is null or p_run is null or p_run !~ '^[A-Za-z0-9:_-]{1,120}$'
 or p_stage is null or p_stage not in ('automate','approve','publish','pause','resume','reconcile','hold','verify')
 or p_status is null or p_status !~ '^[A-Z_]{2,60}$'
 or p_code is null or p_code !~ '^[A-Z0-9_]{2,100}$'
 or (p_revision is not null and p_revision !~ '^[a-f0-9]{64}$')
 then raise exception 'invalid safe outcome'; end if;
 if p_status='PUBLISHED' and not exists(select 1 from icg_side.facebook_deliveries where page_id=p_page and business_key=p_revision and track='talk' and state='PUBLISHED' and (started_at at time zone 'Asia/Seoul')::date=p_day)
 then raise exception 'published delivery required'; end if;
 insert into icg_side.talk_run_events(page_id,slot_date,run_id,stage,status,reason_code,revision)
 values(p_page,p_day,p_run,p_stage,p_status,p_code,p_revision);
 -- Operational stages do not overwrite the normal publishing slot summary.
 if p_stage in ('automate','publish','verify') then
 insert into icg_side.talk_slots(page_id,slot_date,due_at,window_end,status,reason_code,revision)
 values(p_page,p_day,(p_day+time '18:30') at time zone 'Asia/Seoul',(p_day+time '23:59') at time zone 'Asia/Seoul',p_status,p_code,p_revision)
 on conflict(page_id,slot_date) do update set status=excluded.status,reason_code=excluded.reason_code,
 revision=excluded.revision,updated_at=clock_timestamp()
 where icg_side.talk_slots.status<>'PUBLISHED' or excluded.status='PUBLISHED';
 end if;
 return true;
end $$;

create function icg_side.talk_model_state(p_page text,p_key text,p_phase text,p_state text)
returns boolean language plpgsql security invoker set search_path='' as $$
declare changed integer;
begin
 if p_phase is null or p_phase not in ('generation','review') or p_state is null or p_state not in ('RESERVED','COMPLETE','FAILED','UNKNOWN')
 then raise exception 'invalid model state'; end if;
 if p_state='RESERVED' then
 insert into icg_side.talk_model_attempts(page_id,request_key,phase,state) values(p_page,p_key,p_phase,p_state);
 else
 update icg_side.talk_model_attempts set state=p_state,updated_at=clock_timestamp()
 where page_id=p_page and request_key=p_key and phase=p_phase and state='RESERVED';
 get diagnostics changed=row_count;
 if changed<>1 then raise exception 'stale model transition'; end if;
 end if;
 return true;
end $$;

do $$ declare t text; f record;
begin
 foreach t in array array['talk_slots','talk_run_events','talk_model_attempts'] loop
 execute format('alter table icg_side.%I enable row level security',t);
 execute format('revoke all on icg_side.%I from public,anon,authenticated',t);
 execute format('grant select,insert,update on icg_side.%I to service_role',t);
 end loop;
 revoke update on icg_side.talk_run_events from service_role;
 grant usage on sequence icg_side.talk_run_events_id_seq to service_role;
 for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname='icg_side' and p.proname in ('talk_contract_version','talk_record_outcome','talk_model_state') loop
 execute format('revoke all on function %s from public,anon,authenticated',f.signature);
 execute format('grant execute on function %s to service_role',f.signature);
 end loop;
end $$;
notify pgrst,'reload schema';
commit;
